// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQYB29FVuamW0Lqv64eWkE3XVmcezubc8',
    appId: '1:345614720476:web:ffac65c8f4893763bb0319',
    messagingSenderId: '345614720476',
    projectId: 'sensordht22-70d71',
    authDomain: 'sensordht22-70d71.firebaseapp.com',
    databaseURL: 'https://sensordht22-70d71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensordht22-70d71.appspot.com',
    measurementId: 'G-9NM4Y2MER1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTzXsrqmAFNVofjIwIF0jIQqQd65evls',
    appId: '1:345614720476:android:092ea631976d1002bb0319',
    messagingSenderId: '345614720476',
    projectId: 'sensordht22-70d71',
    databaseURL: 'https://sensordht22-70d71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensordht22-70d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdFNHcc8yCtvwEBpJIOEQOOqa58n1LKGQ',
    appId: '1:345614720476:ios:672dd121b1a17152bb0319',
    messagingSenderId: '345614720476',
    projectId: 'sensordht22-70d71',
    databaseURL: 'https://sensordht22-70d71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensordht22-70d71.appspot.com',
    iosBundleId: 'com.example.sensordht22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdFNHcc8yCtvwEBpJIOEQOOqa58n1LKGQ',
    appId: '1:345614720476:ios:c313adac05618b51bb0319',
    messagingSenderId: '345614720476',
    projectId: 'sensordht22-70d71',
    databaseURL: 'https://sensordht22-70d71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensordht22-70d71.appspot.com',
    iosBundleId: 'com.example.sensordht22.RunnerTests',
  );
}
